services:
  - type: web
    name: mishura-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: CACHE_TTL_DAYS
        value: 30
      - key: MAX_CACHE_SIZE
        value: 1000
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0 